#-----------------------------------------
# Title: dupuis-composers.yaml
# Author: Jocelyn Dupuis
# Date: 08/25/2023
# Description: File for Composers API
#-----------------------------------------

# OpenAPI version
openapi: 3.0.0
info:
  title: Composer API
  version: 1.0.0

# Tags
tags:
  - name: Composers

# API Paths
paths:
  /api/composers:
  # GET for findAllComposers
    get:
      tags:
        - Composers
      summary: Returns a list of composer documents
      description: API for returning a list of composers from MongoDB Atlas 
      operationId: findAllComposers
      responses:
        '200':
          description: Composer documents 
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    # POST for createComposer
    post:
      tags:
        - Composers
      summary: Creates a new composer object
      description: API for adding new composer objects
      operationId: createComposer
      requestBody:
        description: Composer's information
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: User added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  # GET for findComposerById
  /api/composers/{id}:
    get:
      tags:
        - Composers
      summary: Returns a composer document
      description: API for returning a single composer object from MOngoDB
      operationId: findComposerById
      parameters:
        - name: id
          in: path
          description: The composerId requested by the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception