#-----------------------------------------
# Title: dupuis-sessions.yaml
# Author: Jocelyn Dupuis
# Date: 09/7/2023
# Description: File for persons API
#-----------------------------------------

# OpenAPI version 
openapi: 3.0.0
info:
  title: Persons API
  version: 1.0.0

# Tags 
tags:
  - name: People

# API Paths
paths:
  /api/persons:
  # GET: findAllPersons
    get:
      tags:
        - People
      summary: Retrieves all People
      responses:
        '200':
          description: Array of persons documents 
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    # POST: createPerson
    post:
      tags:
        - People
      summary: Creates a person
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                dependents:
                  type: array
                  items:
                    type: string
                roles:
                  type: array
                  items:
                    type: string
                birthDate:
                  type: string
                
      responses:
        '200':
          description: Array of person documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception