#-----------------------------------------
# Title: dupuis-composers.yaml
# Author: Jocelyn Dupuis
# Date: 08/25/2023
# Description: File for Composers API
#-----------------------------------------

# OpenAPI version
openapi: 3.0.0
info:
  title: Composer API
  version: 1.0.0

# Tags
tags:
  - name: Composers

# API Paths
paths:
  /api/composers:
  # GET for findAllComposers
    get:
      tags:
        - Composers
      summary: Returns list of composer documents
      description: API for returning list of composers from MongoDB 
      responses:
        '200':
          description: Composer documents 
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    # POST for createComposer
    post:
      tags:
        - Composers
      summary: Creates new composer 
      description: API for adding new composer objects
      requestBody:
        description: Composer's information
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: User added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  # GET for findComposerById
  /api/composers/{id}:
    get:
      tags:
        - Composers
      summary: Returns composer document
      description: API for returning a single composer object from MOngoDB
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    # PUT for updateComposerById
    put:
      tags:
        - Composers
      summary: Update composer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Array of composer documents
        '401':
          description: Invalid composerId
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    # DELETE for deleteComposerById
    delete:
      tags:
        - Composers
      summary: Deletes composer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Composer document
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception